### ISSUE TITLE
New team structure for lispy tracks

### ISSUE THREAD

**Issue by kytrinyx** [exercism/meta#10]
@exercism/lisp @exercism/racket @exercism/clojure I mentioned this in a couple of issues, but I don't want it to get messy, so I'm pulling it out.

There's a new feature on GitHub that lets us nest teams: https://github.com/blog/2378-nested-teams-add-depth-to-your-team-structure

I'd like to have a team that nests one team for each track, named after the track ID.

To get this sorted out, I'm going to need to know:

- what should we name the parent team? `lisps`? `lispy-languages`? Something else?
- for all the individuals on the team, which tracks are you currently maintaining? I'd like to make sure that you're added to the specific tracks rather than the generic one, since that will make the `@`-mentioning more effective.

**TODO**

For each team, ensure:
* team exists
* correct parent team
* repo is on the team with write permissions

- [x] exercism/clojure
- [x] exercism/elisp
- [x] exercism/lfe
- [x] exercism/lisp
- [x] exercism/racket
- [x] exercism/scheme

For each person who responds:
* add them to the correct teams

**Comment by yurrriq** [comment]
I'm involved with all of them, I think, but generally take a backseat role on the lisp track.

**Comment by verdammelt** [comment]
Sounds like a good idea. I'd suggest 'lisps' as the team name. I am currently only involved in `lisp`.

**Comment by wobh** [comment]
I'm mainly involved in the Common Lisp lisp and I think "lisps" is a good general name.

**Comment by kytrinyx** [comment]
OK, cool _lisps_ it is.

**Comment by kytrinyx** [comment]
I've updated the team structure and added new teams.

**Comment by kytrinyx** [comment]
Since we're going to be renaming repos in a heartbeat... should we rename `lisp` to `common-lisp`?

**Comment by verdammelt** [comment]
I vote "yes" on the rename.

**Comment by achengs** [comment]
I know I haven't been much help, but if I were able to make the time it'd
be for clojure and scheme

**Comment by kytrinyx** [comment]
Oh, hello @achengs! I'll add you to clojure and scheme. Thanks!

**Comment by wobh** [comment]
I feel ambivalent about the rename, but if it's good with @verdammelt it's good with me.

**Comment by kytrinyx** [comment]
It is done! Thanks everyone.
