### ISSUE TITLE
Programming language communities overview

### ISSUE THREAD

**Issue by kytrinyx** [exercism/meta#103]
As we move towards the launch of [the new version of Exercism](https://github.com/exercism/v2-feedback/blob/master/README.md) we are going to be ramping up on actively recruiting people to help provide feedback.

Our goal is to get to 100%: everyone who submits a solution and wants feedback should get feedback. Good feedback. You can read more about this aspect of the new site here: http://mentoring.exercism.io/

To do this, we're going to need a lot more information about _where_ we can find language enthusiasts.

As part of this, I'm opening issues in each track asking people to contribute their knowledge and/or research skills to figure out what the language community landscape looks like for that language.

**Comment by rpearce** [comment]
@kytrinyx This is not an actionable comment, but I wanted to say "thank you" on behalf of all learners, educators and mentors out there for the love being put into this. This helps change lives.

**Comment by kytrinyx** [comment]
@rpearce this not-actionable comment made my day 💙 Thank you.

**Comment by sebito91** [comment]
I have a handle on a few sources, hopefully this helps...

1. [awesome-go](https://github.com/avelino/awesome-go/blob/master/README.md)
2. gophers.slack.com (created an exercism channel a while back, but stayed pretty dormant)
3. the discord golang [channel](https://discord.gg/tCv8sAn)

I've put the feelers out to anybody I know in the community so fingers crossed some others will sign up!

**Comment by rpearce** [comment]
@sebito91 Awesome! Do you think you could put this comment in the issue for Go, [Where are the Go communities and enthusiasts?](https://github.com/exercism/go/issues/1111)?

**Comment by sebito91** [comment]
Ah crap, I meant to do just that but put it in the wrong spot...my bad. Thanks for the heads up!

**Comment by kytrinyx** [comment]
I'm going to go ahead and close this, and we will reference it when (and all the related issues) when we start digging into growing the individual tracks. 💙
