### ISSUE TITLE
Ensure that each track config contains a list of file extensions that the language uses

### ISSUE THREAD

**Issue by kytrinyx** [exercism/meta#107]
We will use this for a couple of different purposes:

- **syntax highlighting** - the Prism library can use file extensions to determine which syntax highlighting lexer to use
- **inferring files to submit with CLI** - the CLI can submit an exercise directory, but this often contains temp files, build files, artifacts, etc that we don't care to upload. The extensions will help us decide which files should be submitted

## TODO

- Add support for an `extensions` key in Configlet's `fmt` command
- Script a PR to each track's `config.json` which adds the extensions (we can get extensions from [github/linguist](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml))
- Update the v2 website's `/api/v1/tracks/:track_id` endpoint to send the extensions along as part of the payload
- Update the CLI's `prepare` command to accept and store the extensions as part of the payload
- Update the CLI's `submit` command to filter on the allowed extensions

**Comment by rpottsoh** [comment]
Do you forsee the CLI being able override a tracks expected  (default) extensions on a case by case basis?  I'm just thinking out loud...

**Comment by kytrinyx** [comment]
@rpottsoh the CLI won't need to, as you can always pass a specific list of files, which the CLI will not validate against the list(s)

**Comment by kytrinyx** [comment]
Moved to https://github.com/exercism/exercism/issues/4385
