### ISSUE TITLE
Delphi Track not included in Team list

### ISSUE THREAD

**Issue by rpottsoh** [exercism/meta#11]
@kytrinyx the new structure looks nice, but Delphi has disappeared from the list.  Pascal is there which probably should be Delphi.

**Comment by rpottsoh** [comment]
@kytrinyx I have studied the list of teams more closely, paying more attention to Perl and I understand better what is happening.  I am going to close this issue.

**Comment by kytrinyx** [comment]
I'll rename it to Delphi! I totally missed that, thanks for catching it.

**Comment by rpottsoh** [comment]
Is the root language meant to be at the top of the list or the root track?  I wasn't sure at first and was the reason for the issue.   I didn't really make that clear.  I sighted Perl as a reference since there is more than 1 Perl track.....  So I ended up on the fence about so closed the issue.  Delphi is seen by some as its own language, others consider it object-pascal or simply a dialect of Pascal.  In the final analysis I think you can't lose. ;)

It would serve to make the Delphi track stand out better if it wasn't hidden beneath Pascal.

Just some thoughts thanks.

Sent from my android device.

**Comment by kytrinyx** [comment]
@rpottsoh Since we only have one pascal track, I don't want to add a level between `track-maintainers` and the maintainer track for Delphi. If we add another Pascal track, then we'll group them under "Pascal".

It won't lose visibility, because the teams and their structure do not affect how we show the language on the site.

**Comment by rpottsoh** [comment]
Sounds good like a good plan.  Thanks. 

Sent from my android device.
