### ISSUE TITLE
Repository teams for JavaScript and ECMAScript

### ISSUE THREAD

**Issue by kytrinyx** [exercism/meta#12]
@exercism/javascript @exercism/typescript @exercism/elm @exercism/purescript @exercism/clojurescript @exercism/coffeescript 

I'm working on standardizing a few things, among them, I want every track's maintainer team to be named after the track ID. I'm also using the new nested teams feature on GitHub to help organize things more: https://github.com/blog/2378-nested-teams-add-depth-to-your-team-structure

I'd like to group all the track maintainer teams under the top-level team `track-maintainers`, and then, where we have multiple language variants, group them under a track for the language name.

E.g. for perl, we've got:

```
track-maintainers/
└── perl
    ├── perl5
    └── perl6
```

That means that we need to create a team for ECMAScript (we currently don't have one), and we need a team name for the collective javascript languages. It would make sense to also include the languages that compile/transpile to JavaScript.

1. Does this make sense?
2. What do we call the parent team? We can't call it javascript, because that's what we're using for the javascript track... unless we rename the javascript track ID (which I would rather not do).

**Comment by masters3d** [comment]
how does that work for the track named the same  https://github.com/exercism/xecmascript ?

  are you doing something similar to languages are targeting java vm likd kotlin? kotlin also compiles to js out of the box. 

 maybe you can name the groups like, java ecosystem,  js ecosystem or  java runtime, js engine powered etc.

**Comment by Insti** [comment]
`javascript-family`?

**Comment by masters3d** [comment]
js-family, java-family, apple-family...  I like family

**Comment by NobbZ** [comment]
I'm against adding purescript, elm and clojurescript to the javascript family. I have mixed feelings about coffee...

---

Elm and purescript are heavily inspired by haskell in their syntax, purescript does even support multiple targets aside of JS. Adding other targets to Elm is possible in theory (while some effort needed...). I tend to put them into a group with Haskell or open a team for Functional Programming (which should contain the lispy-team as well).

Clojurescript is more lispy than "JavaScripty" and should therefore a member of the lisp team.

If you add any of these to the JS team, you can add go (gopherjs), idris (idris has a JS backend), haskell (ghcjs), Elixir (ElixirScript is a subset of elixir which transpiles to JavaScript), and probably many, many others asa well to the JS group.

---

CoffeeScript is only another syntax for JS. It does not even bring an own stdlibrary and is transpiled by a simple AST-transform and from this point of view definitively a member of the JS group, BUT it's syntax is different enough to scare anyone away that loves the original C-style JS syntax. Therefore I am not sure if it really belongs into that team...

**Comment by kytrinyx** [comment]
I'm convinced that creating the javascript family is going to confuse more than it will help. I don't think we should do it.

In that case, we will have two teams: javascript and ecmascript.

For those on the @exercism/javascript team, please let me know which of the tracks you maintain (or both, or none—as the case may be.

**Comment by kytrinyx** [comment]
> are you doing something similar to languages are targeting java vm likd kotlin? kotlin also compiles to js out of the box.

No, It made sense for Perl, and probably for the lisps, but I'm not convinced that it adds value.

**Comment by kytrinyx** [comment]
I created the ecmascript team, and added the folks from the javascript team who have contributed to it.

**Comment by matthewmorgan** [comment]
My 2 cents is that Ecmascript makes the most sense to capture at least the JS and ES tracks.  It's the most general.

**Comment by kytrinyx** [comment]
@matthewmorgan would you clarify? Currently I have no nesting, and two teams (named for the track ID of the track that the team maintains).

**Comment by matthewmorgan** [comment]
My thought is that JavaScript is an implementation of EcmaScript, so they could certainly both be nested under EcmaScript.  I don't have much experience with other variations, including CoffeeScript, so I can't speak to that.

**Comment by kytrinyx** [comment]
@matthewmorgan That makes sense. The problem I'm running into is a naming collision. We have an `ecmascript` track, so we cannot have both a parent and child team named `ecmascript`.

**Comment by kotp** [comment]
It could be named `ecmascripts` or `ecma_script` if the split is "normal".  Adding the `s` to the first name suggests a collection of that type of language, perhaps.  This would avoid the name clash, allowing for the organization.

**Comment by kytrinyx** [comment]
`ecmascripts` matches what we did with the `lisps`, too. I like that.

**Comment by rchavarria** [comment]
Nice! So, we'll have `ecmascripts` as parent of `javascript` and `ecmascript`. I like that too.

I'm not sure about grouping other languages such as TypeScript, ClojureScript, CoffeeScript,... They can be transpiled to JavaScript, but I think they have their identity as programming languages themselves. The line that divides ECMAScript and JavaScript is quite thin, if there is a line. I can't talk for all other languages, but I think of them as languages themselves, not as a language that can be *converted* into JavaScript.

**Comment by kytrinyx** [comment]
Alrighty—this is done! Thanks, everyone, for weighing in!
