### ISSUE TITLE
Add nextercism metadata to track configs

### ISSUE THREAD

**Issue by kytrinyx** [exercism/meta#16]
In order to support the new tree-shaped tracks, we need more metadata in the exercises in the track's `config.json`.

Each exercise should have:

* **uuid** (string) - this must be unique to this exercise across all of Exercism's tracks, and must never change. This can be generated using any UUID generator tool. If you don't have a favorite, try https://www.uuidgenerator.net/
* **slug** (string) - this must be unique _within_ a track, but can exist in multiple tracks. The slug can change.
* **core** (boolean) - whether or not this exercise is part of the core series of exercises for the track. If you complete all the core exercises in a track, you complete the track. Exercises that are not core are optional.
* **unlocked_by** (string) - the slug of the exercise that is a prerequisite for getting access to this exercise
* **difficulty** (integer) - a rough estimate of the difficulty level of the exercise on a scale of 1 to 10
* **topics** (array of strings) - topics covered in this exercise

Exercises can be deprecated, in which case they must have the following:

- **uuid**
- **slug**
- **deprecated** (boolean, true)

All other fields can be deleted.

See the full discussion that made the decisions about these fields in: https://github.com/exercism/discussions/issues/159

**Comment by rpottsoh** [comment]
> uuid (string) - this must be unique to this exercise across all of Exercism's tracks, and must never change

@kytrinyx will there be some place to look up uuid's for exercises?  Will the uuid's be added to the canonical-data.json files?  Creating a new uuid is not a big deal, but I don't see a convenient way to determine what a particular exercise's uuid is without fishing it from the config.json from a track that has implemented it.

**Comment by kytrinyx** [comment]
> I don't see a convenient way to determine what a particular exercise's uuid is without fishing it from the config.json from a track that has implemented it.

The UUID needs to be different in every track. So if you have `bob` in Java and `bob` in Go, they need to have different UUIDs.

I'm going to write a service that configlet can use to make sure there are no collisions (and avoid accidents due to copy/paste). So there will be a way to check that a given UUID is not in use.
