### ISSUE TITLE
Remove redundant information from track's config.json

### ISSUE THREAD

**Issue by kytrinyx** [exercism/meta#19]
The `slug` is never used, because we use the track ID to initialize a track in Trackler.
The `repository` can be inferred from the Track ID, so I've changed Trackler to construct the URL rather than reading it from the config.

**Comment by stkent** [comment]
Curious: where do track ids live, if not in the spot the slug is being removed from? Thanks!

**Comment by kytrinyx** [comment]
They are based on the name of the directory of the track, here: https://github.com/exercism/trackler/tree/master/tracks

We detect the names of the directories, and then use that to determine which tracks exist. So ultimately the track ID comes from the name of the repository.

In the nextercism prototype we will likely be explicitly identifying the repository URLs of the tracks and then using local git clones on the servers, but the same basic principle applies.

**Comment by stkent** [comment]
Cool, thanks for explaining!
