### ISSUE TITLE
Generate default maintainers.json file

### ISSUE THREAD

**Issue by kytrinyx** [exercism/meta#20]
Generate a `config/maintainers.json` file for all tracks, containing the following information for each person who is currently in the maintainer team for that track.

```
{
  "github_username": "iHiD",
  "show_on_website": false,
  "alumnus": false,
  "name": "Jeremy Walker",
  "bio": "A friendly, detailed description of your background/interest in the language, to go on the Exercism track page.",
  "link_text": "My Website",
  "link_url": "http://ihid.co.uk",
  "avatar_url": "http://example.com/iHiD.png",
}
```

The only required field is `github_username`.

If `show_on_website` is false or missing, then the maintainer in question will not be featured on the website.

Other optional fields:

- `alumnus`: defaults to false if absent
- `avatar_url`: defaults to your GitHub avatar if `null` or absent.
- `name`: defaults to whatever your public display name on GitHub is. If you have not filled in this field, and there is no name defined on your GitHub profile, we will use your GitHub username as your display name.
- `bio`: if null or absent, it defaults to your public GitHub bio (note that I don't think this is a great default, I would much rather have a bio that is specific to the track). If this is an empty string we will not show a bio at all. Should be about 40 words or so.
- `link_text`: no default. If absent we will use the `link_url` as the anchor.
- `link_url`: no default. If absent we will link to your GitHub profile.

See https://github.com/exercism/discussions/issues/168 for the original discussion and https://github.com/exercism/docs/blob/master/maintaining-a-track/maintainer-configuration.md for the documentation.

**Comment by kytrinyx** [comment]
I've written the script to submit the pull requests. I'm going to submit this to a handful of tracks, then wait for feedback.

**Comment by iHiD** [comment]
@kytrinyx Thanks for the canaries.

I wonder if it would be better to leave `bio` and `avatar_url` null (but with specified keys) by default. Our import script will then read GitHub to get this information as it imports. This means that if a maintainer is happy just to reuse their Github bio/image they don't have to remember to update it here if they update it here if they update it there (presuming we do a daily check for changes to Github).

Thoughts?

**Comment by kytrinyx** [comment]
@iHiD Yeah, I think that would be better.  I'll update the canary PRs.

Also, a daily check sounds good.

**Comment by kytrinyx** [comment]
@iHiD Actually—should we put nulls everywhere except the username and show_on_website?

**Comment by iHiD** [comment]
> should we put nulls everywhere except the username and show_on_website?

@kytrinyx I think that's a good idea, yes. However, I like the default link to someone's Github profile in your PR. I think that's a sensible default, so I'd leave that in. Thoughts?

**Comment by kytrinyx** [comment]
@iHiD We have their username, so we can construct the link to their GitHub profile in our daily sync. I think that if we are syncing some of it, we should sync all of it :)

**Comment by kytrinyx** [comment]
FYI: I've updated the canary PRs @iHiD

**Comment by Insti** [comment]
I'm a bit confused. (I've been away on holiday and have not been following the process so this issue linked from the exercism/ruby PR is my first introduction to this topic.)

In https://github.com/exercism/ruby/pull/693/files it would seem to me that the only thing necessary to have would ideally be the github username?

Do all the keys need to be present?
Is there a difference between a key being `null` and not present?
Has the OP of this issue been updated to reflect the ongoing discussion?
What does a bio look like when rendered?

**Comment by iHiD** [comment]
@Insti Welcome back - hope your holiday was nice :)

> Do all the keys need to be present?

No 

> Is there a difference between a key being null and not present?

There's none.

> Has the OP of this issue been updated to reflect the ongoing discussion?

Yes

> What does a bio look like when rendered?

Something like this (this isn't correct yet - but along these lines): 
<img width="238" alt="screen shot 2017-07-24 at 15 55 22" src="https://user-images.githubusercontent.com/286476/28529444-79edf354-7088-11e7-8e0c-23c5947deff8.png">

> it would seem to me that the only thing necessary to have would ideally be the github username?

We felt that putting the other fields in make it easy for maintainers to update without having to grok the issues/docs to know what to do. If you want to always keep it the same as Github you can delete the keys. If you want to change them, then the keys are there so it's easy. That's the logic - not saying it's right :)

**Comment by kotp** [comment]
I am ok with it, with the feeling that the individual maintainers should maintain their own entries, aside from unfortunate events, due to whatever their feeling is about publicity, attention, etc.

In other words, for the Ruby track, I would not feel comfortable adding details on @Insti entries, for example.

**Comment by Insti** [comment]
I agree that maintainers should maintain their own entries.

**Comment by kytrinyx** [comment]
> I agree that maintainers should maintain their own entries.

Yes, 100%—the only exception is turning "alumnus" to true if someone has been away for a long time, and is not responding to pings (I do try to send personal emails to people before I take them off teams, etc, but I don't know that I can continue to do that indefinitely. We'll see)

**Comment by wolf99** [comment]
This seems to have skipped the C track... was that an oversight or was the C track on the naughty step? (all other tracks currently present seem to have it BTW)

**Comment by kotp** [comment]
We likely missed it.

**Comment by wolf99** [comment]
OK, I'll add a PR over there for it so 👍
