### ISSUE TITLE
Cut new configlet release

### ISSUE THREAD

**Issue by kytrinyx** [exercism/meta#22]
In order to cut a new release of Configlet with the new behavior that @nywilken added (verify presence of test file), we need to fix some of the tracks.

Most likely this is a missing or incorrect `/test_pattern/. Potentially these are actually missing test suites.

- [x] bash
- [x] coffeescript
- [x] coldfusion
- [x] coq https://github.com/exercism/coq/issues/21
- [x] d
- [x] factor
- [x] groovy
- [x] haxe
- [x] ocaml https://github.com/exercism/ocaml/pull/212
- [x] sml https://github.com/exercism/sml/pull/64

**Comment by nywilken** [comment]
@kytrinyx thanks for moving this along so quickly. Let me know if there is anything I can assist with at this point.

**Comment by kytrinyx** [comment]
I think we're good! Just waiting on responses in SML and Coq.

**Comment by kytrinyx** [comment]
... and SML merged theirs!

**Comment by kytrinyx** [comment]
I submitted a workaround to the Coq track so we can release. https://github.com/exercism/coq/pull/22

**Comment by kytrinyx** [comment]
Released: https://github.com/exercism/configlet/releases/tag/v3.2.0
