### ISSUE TITLE
Which programming languages have logos?

### ISSUE THREAD

**Issue by kytrinyx** [exercism/meta#24]
This weekend we're designing individual icons for each language track on Nextercism. We've found that trying to find all the official logos is taking us ages and we are hoping you can help make the process quicker for us!

To help speed this work, we're attempting a quick crowdsouring project  **(Issues linked below)** to compile information about each language that we have represented on Exercism.

These are about the _programming language_ itself, not the language track on Exercism.

* Is there an official logo for the language?
* If not, is there an unofficial logo for the language?
* [link to the logo]
* What are the usage rights of that logo?

We will likely do "artist impressions" of logos rather than adapting them directly, as that will give us a lot more freedom in terms of usage rights, but it's still useful to know what the terms are on the existing logos.

I'm opening one issue per language track here in the meta repository, so that we have an easy way to keep track of what is done and not.

**Comment by andrew** [comment]
We've found quite a few for @librariesio: https://libraries.io/languages all available as a rails asset gem: https://github.com/librariesio/pictogram

**Comment by iHiD** [comment]
@andrew That is so sickeningly helpful. Thank you 💙

**Comment by kytrinyx** [comment]
Holy smokes, @andrew, that's brilliant!

**Comment by kytrinyx** [comment]
This is it. Could not have done this without @m-a-ge!!! 🌷

**Comment by iHiD** [comment]
Massive thanks to everyone and especially @m-a-ge! You have just made our lives **much** easier :)
