### ISSUE TITLE
C / official or unofficial logo

### ISSUE THREAD

**Issue by kytrinyx** [exercism/meta#26]
As described in https://github.com/exercism/meta/issues/24, this weekend we're designing proper icons for each of the language tracks on Exercism.

In order to help speed us through this work, it would be helpful to know whether or not the language has a logo, whether official or unofficial, what that logo is, and what the usage rights of it are.

If you know things, awesome! Drop that knowledge below. If you don't but want to help do research, we will be very grateful.

Here's a template for you to fill out:

```
### Official Logo

### Unofficial Logo

### Link to Logo

### License, Usage Rights
```

For each heading, please list what you know or find out. If something is irrelevant due to something listed in an earlier heading, say `n/a` (not applicable).

We did some research a while back, and might have some useful information at the bottom of the [README.md](https://github.com/exercism/c/blob/master/README.md). (Look for "C icon")

You can see whatever icon we've put together for the track in the [img directory](https://github.com/exercism/c/tree/master/img) of the track. Sometimes this is based on something official, sometimes it's just desperation made tangible. (You'll see why we're working with real designers.)

**Comment by ryanflach** [comment]
### Official Logo
Unknown.

### Unofficial Logo
Most popular appear to be the cover of The C Programming Language book, the icon already used by exercism,  and the vector linked below.

![screen shot 2017-08-05 at 5 26 28 pm](https://user-images.githubusercontent.com/11306104/28999421-69312b92-7a03-11e7-9268-a1a8756b5442.png)


### Link to Logo
https://seeklogo.com/vector-logo/306166/c-programming-language
Direct file: [c-programming-language-vector-logo-45EED0B09A-seeklogo.com.zip](https://github.com/exercism/meta/files/1202743/c-programming-language-vector-logo-45EED0B09A-seeklogo.com.zip)

Note: This is a svg vector.

### License, Usage Rights
None listed.

**Comment by iHiD** [comment]
Very helpful. Thank you!
