### ISSUE TITLE
C++ / official or unofficial logo

### ISSUE THREAD

**Issue by kytrinyx** [exercism/meta#28]
As described in https://github.com/exercism/meta/issues/24, this weekend we're designing proper icons for each of the language tracks on Exercism.

In order to help speed us through this work, it would be helpful to know whether or not the language has a logo, whether official or unofficial, what that logo is, and what the usage rights of it are.

If you know things, awesome! Drop that knowledge below. If you don't but want to help do research, we will be very grateful.

Here's a template for you to fill out:

```
### Official Logo

### Unofficial Logo

### Link to Logo

### License, Usage Rights
```

For each heading, please list what you know or find out. If something is irrelevant due to something listed in an earlier heading, say `n/a` (not applicable).

We did some research a while back, and might have some useful information at the bottom of the [README.md](https://github.com/exercism/cpp/blob/master/README.md). (Look for "C++ icon")

You can see whatever icon we've put together for the track in the [img directory](https://github.com/exercism/cpp/tree/master/img) of the track. Sometimes this is based on something official, sometimes it's just desperation made tangible. (You'll see why we're working with real designers.)

**Comment by ShadowMitia** [comment]
### Official Logo
https://github.com/isocpp/logos

The logo is the one found at https://isocpp.org/, which is the main site for the C++ Foundation.

### Unofficial Logo
n/a

### Link to Logo
https://github.com/isocpp/logos
https://github.com/isocpp/logos/blob/master/cpp_logo.svg
https://github.com/isocpp/logos/blob/master/cpp_logo.png

### License, Usage Rights
https://isocpp.org/home/terms-of-use

The relevant part:

 
> The “Standard C++ Foundation” name and stylized “C++” logo are trademarks of the Standard C++ Foundation and may not be used without permission from the Foundation. Permission is hereby granted:
> 
> -  to use the unaltered logo in conjunction with any product (including but not limited to a C++ compiler implementation or tool, or a product written using C++) or material (including but not limited to product packaging, documentation, educational material, user group meeting information, or blog post) that is related to the standardized C++ language or working drafts thereof (including the C++ International Standard and related Technical Specifications, whether published or draft, but excluding nonstandard vendor-specific extensions), and that does not imply endorsement of a product or organization (including but not limited to that it is not being used as part of another organization’s logo); and
>  -   to use the “Standard C++ Foundation” name to refer to the Standard C++ Foundation or to the isocpp.org website, optionally with a courtesy link to isocpp.org or isocpp.org/about, but not in a way that claims or implies affiliation with or endorsement of a product or organization.
> 
> In general, we want the logo to be used as widely as possible to indicate material related to the portable C++ and its applications, without implicitly endorsing something or someone. Please ask first before using a derived version of the logo or when in doubt.

**Comment by kytrinyx** [comment]
This is super helpful, thank you! 🌷
