### ISSUE TITLE
CoffeeScript / official or unofficial logo

### ISSUE THREAD

**Issue by kytrinyx** [exercism/meta#31]
As described in https://github.com/exercism/meta/issues/24, this weekend we're designing proper icons for each of the language tracks on Exercism.

In order to help speed us through this work, it would be helpful to know whether or not the language has a logo, whether official or unofficial, what that logo is, and what the usage rights of it are.

If you know things, awesome! Drop that knowledge below. If you don't but want to help do research, we will be very grateful.

Here's a template for you to fill out:

```
### Official Logo

### Unofficial Logo

### Link to Logo

### License, Usage Rights
```

For each heading, please list what you know or find out. If something is irrelevant due to something listed in an earlier heading, say `n/a` (not applicable).

We did some research a while back, and might have some useful information at the bottom of the [README.md](https://github.com/exercism/coffeescript/blob/master/README.md). (Look for "CoffeeScript icon")

You can see whatever icon we've put together for the track in the [img directory](https://github.com/exercism/coffeescript/tree/master/img) of the track. Sometimes this is based on something official, sometimes it's just desperation made tangible. (You'll see why we're working with real designers.)

**Comment by ryanflach** [comment]
### Official Logo
Yes.
### Unofficial Logo
N/A
### Link to Logo
https://upload.wikimedia.org/wikipedia/en/1/1c/CoffeeScript-logo.png
### License, Usage Rights
The information in https://github.com/exercism/coffeescript/blob/master/README.md#coffeescript-icon appears to be current.

**Comment by iHiD** [comment]
Wonderful. Thank you!
