### ISSUE TITLE
Common Lisp / official or unofficial logo

### ISSUE THREAD

**Issue by kytrinyx** [exercism/meta#33]
As described in https://github.com/exercism/meta/issues/24, this weekend we're designing proper icons for each of the language tracks on Exercism.

In order to help speed us through this work, it would be helpful to know whether or not the language has a logo, whether official or unofficial, what that logo is, and what the usage rights of it are.

If you know things, awesome! Drop that knowledge below. If you don't but want to help do research, we will be very grateful.

Here's a template for you to fill out:

```
### Official Logo

### Unofficial Logo

### Link to Logo

### License, Usage Rights
```

For each heading, please list what you know or find out. If something is irrelevant due to something listed in an earlier heading, say `n/a` (not applicable).

We did some research a while back, and might have some useful information at the bottom of the [README.md](https://github.com/exercism/lisp/blob/master/README.md). (Look for "Common Lisp icon")

You can see whatever icon we've put together for the track in the [img directory](https://github.com/exercism/lisp/tree/master/img) of the track. Sometimes this is based on something official, sometimes it's just desperation made tangible. (You'll see why we're working with real designers.)

**Comment by ilya-khadykin** [comment]
### Official Logo
![](https://common-lisp.net/static/imgs/lisplogo.png)

It's from official website - https://common-lisp.net/ (not sure about its license)
### Unofficial Logo
I've seen some strange pics like this one for example:
![](http://orig02.deviantart.net/fc79/f/2015/208/b/5/common_lisp_wallpaper__retina_with_original_svg__by_pocket7878-d9301iq.png)

Looks like someone tried to be funny
### Link to Logo
https://common-lisp.net/

### License, Usage Rights
Not sure, the language itself is available under MIT license (from wiki):
>In January 2015 Corman Lisp has been published under MIT license.

Q: Is exercism.io using official logo?
A: No?
![](http://exercism.io/tracks/lisp/icon)

**Comment by iHiD** [comment]
I have never seen that logo before! Thanks :)
