### ISSUE TITLE
Crystal / official or unofficial logo

### ISSUE THREAD

**Issue by kytrinyx** [exercism/meta#35]
As described in https://github.com/exercism/meta/issues/24, this weekend we're designing proper icons for each of the language tracks on Exercism.

In order to help speed us through this work, it would be helpful to know whether or not the language has a logo, whether official or unofficial, what that logo is, and what the usage rights of it are.

If you know things, awesome! Drop that knowledge below. If you don't but want to help do research, we will be very grateful.

Here's a template for you to fill out:

```
### Official Logo

### Unofficial Logo

### Link to Logo

### License, Usage Rights
```

For each heading, please list what you know or find out. If something is irrelevant due to something listed in an earlier heading, say `n/a` (not applicable).

We did some research a while back, and might have some useful information at the bottom of the [README.md](https://github.com/exercism/crystal/blob/master/README.md). (Look for "Crystal icon")

You can see whatever icon we've put together for the track in the [img directory](https://github.com/exercism/crystal/tree/master/img) of the track. Sometimes this is based on something official, sometimes it's just desperation made tangible. (You'll see why we're working with real designers.)

**Comment by ilya-khadykin** [comment]
### Official Logo
![](https://crystal-lang.org/assets/media/crystal_logo-stacked_version.svg)

Other version of the logo as well as guidelines  can be found on the official website: https://crystal-lang.org/media/
### Unofficial Logo
N/A

### Link to Logo
https://crystal-lang.org/assets/media/crystal_logo-stacked_version.svg

`librariesio/pictogram` (MIT license): https://raw.githubusercontent.com/librariesio/pictogram/master/vendor/assets/images/crystal/crystal.png
### License, Usage Rights
From official website:
> Crystal is licensed under the Apache License, Version 2.0
MIT version is also available (see above)

Q: Is exercism.io using official logo?
A: Modified version (looks like it's against official guidelines):
![](http://exercism.io/tracks/crystal/icon)

**Comment by NobbZ** [comment]
According to the linked paged (https://crystal-lang.org/media/) [emphasis added by me]:

> Don’t do these things with the Crystal logos and brand:
> * **Change their colors**, dimensions or add your own text.

So we have to change the logo unless we have explicit permission to do so!

**Comment by kytrinyx** [comment]
I wonder if this changed after I found the logo. The notation that we made sounds very much like what we added when we found a wikipedia entry that said public domain, and couldn't find anything official.

Wikipedia now agrees, though, we are not within the usage rights: https://en.wikipedia.org/wiki/File:The_Crystal_programming_language_logo.svg

**Comment by NobbZ** [comment]
> The notation that we made sounds very much like what we added when we found a wikipedia entry that said public domain, and couldn't find anything official.

So, this teaches us:

Right beneath every single logo in the repository, there needs to be a single document which describes at least the following:

* source of the original logo/picture used as base for the exercism version, explicitely mention if logo was designed from scratch
* the changes made vs the original (if applicable)
* Assumed license and sources that made us believe this license is valid (links should be perma-links, also the date should be stated explicitely, if available also put in a link to the exact version in wayback-machine); Make sure, that any dates and perma-links are recent when the logo itself is getting updated.
* If available a copy of the document that allows us to do things with the logo that usually are permitted by the license

**Comment by kytrinyx** [comment]
> there needs to be a single document which describes [...]

Yes, I think we definitely need to have all of this documented, as close as possible to where we store the logos.

**Comment by kytrinyx** [comment]
Thanks so much for both the research and the discussion!
