### ISSUE TITLE
Delphi Pascal / official or unofficial logo

### ISSUE THREAD

**Issue by kytrinyx** [exercism/meta#38]
As described in https://github.com/exercism/meta/issues/24, this weekend we're designing proper icons for each of the language tracks on Exercism.

In order to help speed us through this work, it would be helpful to know whether or not the language has a logo, whether official or unofficial, what that logo is, and what the usage rights of it are.

If you know things, awesome! Drop that knowledge below. If you don't but want to help do research, we will be very grateful.

Here's a template for you to fill out:

```
### Official Logo

### Unofficial Logo

### Link to Logo

### License, Usage Rights
```

For each heading, please list what you know or find out. If something is irrelevant due to something listed in an earlier heading, say `n/a` (not applicable).

We did some research a while back, and might have some useful information at the bottom of the [README.md](https://github.com/exercism/delphi/blob/master/README.md). (Look for "Delphi Pascal icon")

You can see whatever icon we've put together for the track in the [img directory](https://github.com/exercism/delphi/tree/master/img) of the track. Sometimes this is based on something official, sometimes it's just desperation made tangible. (You'll see why we're working with real designers.)

**Comment by rpottsoh** [comment]
Are you looking for the native logo for the languagr or the icon that may have had its colors adjusted for the old site?

**Comment by iHiD** [comment]
Native logo please. We will be recolouring etc.

**Comment by rpottsoh** [comment]
![image](https://user-images.githubusercontent.com/6978003/28999656-cb0677aa-7a1c-11e7-975d-25ed65555cc8.png)

Native Logo: https://rpottsoh.keybase.pub/Delphi.png
Permission to use the logo was granted by Jim McKeeth of Embarcadero as long as the track is called Delphi.

**Comment by kytrinyx** [comment]
Perfect. Thank you @rpottsoh!
