### ISSUE TITLE
Remove support for "problems" key in config.json

### ISSUE THREAD

**Issue by kytrinyx** [exercism/meta#4]
None of the tracks have a problems key. Trackler and configlet can stop checking.

**Comment by Insti** [comment]
Todo list:

- [x] Trackler https://github.com/exercism/trackler/pull/65
- [x] Configlet https://github.com/exercism/configlet/pull/16

**Comment by Insti** [comment]
Todo list:

- [ ] Trackler
- [ ] Configlet

**Comment by kytrinyx** [comment]
I've submitted a PR for this in configlet.

**Comment by kytrinyx** [comment]
Aaaaand done! Thank you for your help, @Insti
