### ISSUE TITLE
Elixir / official or unofficial logo

### ISSUE THREAD

**Issue by kytrinyx** [exercism/meta#40]
As described in https://github.com/exercism/meta/issues/24, this weekend we're designing proper icons for each of the language tracks on Exercism.

In order to help speed us through this work, it would be helpful to know whether or not the language has a logo, whether official or unofficial, what that logo is, and what the usage rights of it are.

If you know things, awesome! Drop that knowledge below. If you don't but want to help do research, we will be very grateful.

Here's a template for you to fill out:

```
### Official Logo

### Unofficial Logo

### Link to Logo

### License, Usage Rights
```

For each heading, please list what you know or find out. If something is irrelevant due to something listed in an earlier heading, say `n/a` (not applicable).

We did some research a while back, and might have some useful information at the bottom of the [README.md](https://github.com/exercism/elixir/blob/master/README.md). (Look for "Elixir icon")

You can see whatever icon we've put together for the track in the [img directory](https://github.com/exercism/elixir/tree/master/img) of the track. Sometimes this is based on something official, sometimes it's just desperation made tangible. (You'll see why we're working with real designers.)

**Comment by samdvr** [comment]
### Unofficial Logo
![Unofficial Logo](https://upload.wikimedia.org/wikipedia/commons/9/92/Official_Elixir_logo.png)


### Link to Logo
(https://upload.wikimedia.org/wikipedia/commons/9/92/Official_Elixir_logo.png)

## Licence 
Rights and any usage of the logo should be with the permission from http://plataformatec.com.br/

**Comment by iHiD** [comment]
@samdvr Thank you! Any idea on usage rights?

**Comment by samdvr** [comment]
@iHiD updated the post with license and usage rights.

**Comment by iHiD** [comment]
@samdvr Thank you!

@kytrinyx Could you reach out to the Elixir team if we haven't previously got permission please?
