### ISSUE TITLE
Emacs Lisp / official or unofficial logo

### ISSUE THREAD

**Issue by kytrinyx** [exercism/meta#42]
As described in https://github.com/exercism/meta/issues/24, this weekend we're designing proper icons for each of the language tracks on Exercism.

In order to help speed us through this work, it would be helpful to know whether or not the language has a logo, whether official or unofficial, what that logo is, and what the usage rights of it are.

If you know things, awesome! Drop that knowledge below. If you don't but want to help do research, we will be very grateful.

Here's a template for you to fill out:

```
### Official Logo

### Unofficial Logo

### Link to Logo

### License, Usage Rights
```

For each heading, please list what you know or find out. If something is irrelevant due to something listed in an earlier heading, say `n/a` (not applicable).

We did some research a while back, and might have some useful information at the bottom of the [README.md](https://github.com/exercism/elisp/blob/master/README.md). (Look for "Emacs Lisp icon")

You can see whatever icon we've put together for the track in the [img directory](https://github.com/exercism/elisp/tree/master/img) of the track. Sometimes this is based on something official, sometimes it's just desperation made tangible. (You'll see why we're working with real designers.)

**Comment by ilya-khadykin** [comment]
### Official Logo
Could not find one

On wiki about the language https://en.wikipedia.org/wiki/Emacs_Lisp Emacs logo is used:
![](https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/EmacsIcon.svg/120px-EmacsIcon.svg.png)
### Unofficial Logo
N/A

### Link to Logo
N/A

librariesio/pictogram (MIT license): https://raw.githubusercontent.com/librariesio/pictogram/master/vendor/assets/images/emacs/emacs.png (again, Emacs, not the language)
### License, Usage Rights
N/A

Q: Is exercism.io using official logo?
A: N/A,
![](http://exercism.io/tracks/elisp/icon)

**Comment by kytrinyx** [comment]
Yeah, that's the only thing I found back when I looked, as well. Thanks!
