### ISSUE TITLE
Erlang / official or unofficial logo

### ISSUE THREAD

**Issue by kytrinyx** [exercism/meta#43]
As described in https://github.com/exercism/meta/issues/24, this weekend we're designing proper icons for each of the language tracks on Exercism.

In order to help speed us through this work, it would be helpful to know whether or not the language has a logo, whether official or unofficial, what that logo is, and what the usage rights of it are.

If you know things, awesome! Drop that knowledge below. If you don't but want to help do research, we will be very grateful.

Here's a template for you to fill out:

```
### Official Logo

### Unofficial Logo

### Link to Logo

### License, Usage Rights
```

For each heading, please list what you know or find out. If something is irrelevant due to something listed in an earlier heading, say `n/a` (not applicable).

We did some research a while back, and might have some useful information at the bottom of the [README.md](https://github.com/exercism/erlang/blob/master/README.md). (Look for "Erlang icon")

You can see whatever icon we've put together for the track in the [img directory](https://github.com/exercism/erlang/tree/master/img) of the track. Sometimes this is based on something official, sometimes it's just desperation made tangible. (You'll see why we're working with real designers.)

**Comment by NobbZ** [comment]
### Official Logo

![http://www.erlang.org/img/erlang.png](http://www.erlang.org/img/erlang.png)

### Unofficial Logo

None that I'm aware off

### Link to Logo

http://www.erlang.org/img/erlang.png

### License, Usage Rights

Not sure. I did not found anything on the erlang page or the github repo, thatsaid anything about the logo.

Erlang itself is currently Apache 2.0:

https://github.com/erlang/otp/blob/master/LICENSE.txt

**Comment by kytrinyx** [comment]
I think I remember seeing something about how the Erlang logo is considered a generic shape, and as such cannot be copyrighted. I'll see if I can find a reference to that.

**Comment by kytrinyx** [comment]
Found it: https://commons.wikimedia.org/wiki/File:Erlang_logo.png

> This image only consists of simple geometric shapes or text. It does not meet the threshold of originality needed for copyright protection, and is therefore in the public domain. Although it is free of copyright restrictions, this image may still be subject to other restrictions. See WP:PD#Fonts and typefaces or Template talk:PD-textlogo for more information.
