### ISSUE TITLE
F# / official or unofficial logo

### ISSUE THREAD

**Issue by kytrinyx** [exercism/meta#44]
As described in https://github.com/exercism/meta/issues/24, this weekend we're designing proper icons for each of the language tracks on Exercism.

In order to help speed us through this work, it would be helpful to know whether or not the language has a logo, whether official or unofficial, what that logo is, and what the usage rights of it are.

If you know things, awesome! Drop that knowledge below. If you don't but want to help do research, we will be very grateful.

Here's a template for you to fill out:

```
### Official Logo

### Unofficial Logo

### Link to Logo

### License, Usage Rights
```

For each heading, please list what you know or find out. If something is irrelevant due to something listed in an earlier heading, say `n/a` (not applicable).

We did some research a while back, and might have some useful information at the bottom of the [README.md](https://github.com/exercism/fsharp/blob/master/README.md). (Look for "F# icon")

You can see whatever icon we've put together for the track in the [img directory](https://github.com/exercism/fsharp/tree/master/img) of the track. Sometimes this is based on something official, sometimes it's just desperation made tangible. (You'll see why we're working with real designers.)

**Comment by TeaDrivenDev** [comment]
### Official Logo

F# has an official logo designed to order from the F# Software Foundation. It is already in use for the F# track on the current Exercism site with permission from the FSSF.

### Unofficial Logo

There are no unofficial logos for F# in common use.

### Link to Logo

The F# Software Foundation has a page containing image resources and guidelines for using the logo: http://foundation.fsharp.org/logo

### License, Usage Rights

> Usage of the logo is allowed, provided that the logo remains unchanged and the logo is used in a way that is supportive of the mission statement of the F# Software Foundation. Do not alter the image shape, color, or proportions. Do not use the logo in a context which could imply representation of the F# Software Foundation directly. For example, do not use the logo alone as your profile image for social media accounts, e.g. Facebook and Twitter.

Outside of the legalese, color changes to fit a particular site design are usually possible within limits (generally the same or different shades of the same basic color). For anything else than the original colors or the variant currently used by Exercism, the final design should be run by the FSSF again to make sure they're happy with it.

**Comment by iHiD** [comment]
Super helpful. Thank you!
