### ISSUE TITLE
Factor / official or unofficial logo

### ISSUE THREAD

**Issue by kytrinyx** [exercism/meta#45]
As described in https://github.com/exercism/meta/issues/24, this weekend we're designing proper icons for each of the language tracks on Exercism.

In order to help speed us through this work, it would be helpful to know whether or not the language has a logo, whether official or unofficial, what that logo is, and what the usage rights of it are.

If you know things, awesome! Drop that knowledge below. If you don't but want to help do research, we will be very grateful.

Here's a template for you to fill out:

```
### Official Logo

### Unofficial Logo

### Link to Logo

### License, Usage Rights
```

For each heading, please list what you know or find out. If something is irrelevant due to something listed in an earlier heading, say `n/a` (not applicable).

We did some research a while back, and might have some useful information at the bottom of the [README.md](https://github.com/exercism/factor/blob/master/README.md). (Look for "Factor icon")

You can see whatever icon we've put together for the track in the [img directory](https://github.com/exercism/factor/tree/master/img) of the track. Sometimes this is based on something official, sometimes it's just desperation made tangible. (You'll see why we're working with real designers.)

**Comment by ilya-khadykin** [comment]
### Official Logo
From official website http://factorcode.org/:
![](http://factorcode.org/logo.png)
### Unofficial Logo
N/A

### Link to Logo
http://factorcode.org/

### License, Usage Rights
From official website http://factorcode.org/:
> Full source code for the Factor project is available under a BSD license.

But still not sure about logo

Q: Is exercism.io using official logo?
A: Nope,
![](http://exercism.io/tracks/factor/icon)

**Comment by kytrinyx** [comment]
Thank you! Yeah, not quite official logo there :-)
