### ISSUE TITLE
Fortran / official or unofficial logo

### ISSUE THREAD

**Issue by kytrinyx** [exercism/meta#46]
As described in https://github.com/exercism/meta/issues/24, this weekend we're designing proper icons for each of the language tracks on Exercism.

In order to help speed us through this work, it would be helpful to know whether or not the language has a logo, whether official or unofficial, what that logo is, and what the usage rights of it are.

If you know things, awesome! Drop that knowledge below. If you don't but want to help do research, we will be very grateful.

Here's a template for you to fill out:

```
### Official Logo

### Unofficial Logo

### Link to Logo

### License, Usage Rights
```

For each heading, please list what you know or find out. If something is irrelevant due to something listed in an earlier heading, say `n/a` (not applicable).

We did some research a while back, and might have some useful information at the bottom of the [README.md](https://github.com/exercism/fortran/blob/master/README.md). (Look for "Fortran icon")

You can see whatever icon we've put together for the track in the [img directory](https://github.com/exercism/fortran/tree/master/img) of the track. Sometimes this is based on something official, sometimes it's just desperation made tangible. (You'll see why we're working with real designers.)

**Comment by ilya-khadykin** [comment]
### Official Logo
Not sure that there is an official logo

### Unofficial Logo
There are a lot of other variations (mostly 'Fortran' text), but this one looks like the best pick:
![](https://upload.wikimedia.org/wikipedia/commons/b/b6/Fortran.png)

### Link to Logo
https://commons.wikimedia.org/wiki/File:Fortran.png

`librariesio/pictogram` (MIT license): https://raw.githubusercontent.com/librariesio/pictogram/master/vendor/assets/images/fortran/fortran.png
### License, Usage Rights
GNU Free Documentation License and MIT versions are available (see above)

Q: Is exercism.io using official logo?
A: No logo is used, only placeholder:
![](http://exercism.io/tracks/fortran/icon)

**Comment by kytrinyx** [comment]
Thanks @m-a-ge!

There was also some discussion here: https://github.com/exercism/fortran/issues/5

**Comment by ilya-khadykin** [comment]
@kytrinyx, thanks for the reference

**Comment by antoinetavant** [comment]
### Official Logo
none to my knowledge
### Unofficial Logo
From the[ 'file-icons' extension](https://github.com/file-icons/atom/) used in Atom :

![the image](https://cdn.rawgit.com/file-icons/source/master/svg/Fortran.svg)

### Link to Logo

https://cdn.rawgit.com/file-icons/source/master/svg/Fortran.svg
### License, Usage Rights
[MIT Licence](https://github.com/file-icons/atom/blob/master/LICENSE.md)

> Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
