### ISSUE TITLE
Haskell / official or unofficial logo

### ISSUE THREAD

**Issue by kytrinyx** [exercism/meta#49]
As described in https://github.com/exercism/meta/issues/24, this weekend we're designing proper icons for each of the language tracks on Exercism.

In order to help speed us through this work, it would be helpful to know whether or not the language has a logo, whether official or unofficial, what that logo is, and what the usage rights of it are.

If you know things, awesome! Drop that knowledge below. If you don't but want to help do research, we will be very grateful.

Here's a template for you to fill out:

```
### Official Logo

### Unofficial Logo

### Link to Logo

### License, Usage Rights
```

For each heading, please list what you know or find out. If something is irrelevant due to something listed in an earlier heading, say `n/a` (not applicable).

We did some research a while back, and might have some useful information at the bottom of the [README.md](https://github.com/exercism/haskell/blob/master/README.md). (Look for "Haskell icon")

You can see whatever icon we've put together for the track in the [img directory](https://github.com/exercism/haskell/tree/master/img) of the track. Sometimes this is based on something official, sometimes it's just desperation made tangible. (You'll see why we're working with real designers.)

**Comment by pushcx** [comment]
## Official Logo

[Branding page](https://wiki.haskell.org/Brand) has the official logo.

[Origin](https://wiki.haskell.org/ThompsonWheelerLogo) of the logo in a 2009 contest.

### Unofficial Logo

The official Haskell.org homepage uses a [purple variation](https://github.com/haskell-infra/hl/blob/master/static/img/haskell-logo.svg).

The icon currently in the img directory is the correct shape but in unfamiliar colors.

The Haskell logo is officially grayscale (see wiki link) and the branding page has some blue tones, but the [Haskell homepage](http://haskell.org) uses a purple variation. I [can't see a git history](https://github.com/haskell-infra/hl/blob/master/static/img/haskell-logo.svg) or explicit discussion of the colors, though it's mentioned in [this PR](https://github.com/haskell-infra/hl/pull/162#issuecomment-218369179) and these two issues: [165](https://github.com/haskell-infra/hl/issues/165) and [215](https://github.com/haskell-infra/hl/issues/215). I think it's just an individual's choice to spruce it up a bit.

**Comment by iHiD** [comment]
@pushcx Brilliant. Thank you. Do you have any information on usage rights?

**Comment by pushcx** [comment]
Nothing explicit, no. The [logo competition](https://wiki.haskell.org/Haskell_logos/New_logo_ideas) mentions "The image should be freely available (a suitable freely distributable license)." but neither the already-linked wiki page or [the artist's copy](http://static.igstan.ro/haskell-logos/) mention a license.

Wikipedia [considers it](https://commons.wikimedia.org/wiki/File:Haskell-Logo.svg) public domain. I looked back on the haskell-cafe mailing list and can find [the contest being planned](https://mail.haskell.org/pipermail/haskell-cafe/2009-January/052777.html) but I couldn't spot this one being submitted there (I certainly could've missed it), maybe there's also a usenet group?

**Comment by iHiD** [comment]
OK - perfect. I'm happy to trust Wikipedia on this! Thank you so much for digging!
