### ISSUE TITLE
Rename TRACK_HINTS.md

### ISSUE THREAD

**Issue by kytrinyx** [exercism/meta#5]
The `exercises/TRACK_HINTS.md` file was a bit confusingly named. Better than the previous name, `./SETUP.md`, but still not great.

We had a discussion in https://github.com/exercism/discussions/issues/147 to come up with a better one, and the winner is `docs/EXERCISE_README_INSERT.md`.

TODO:

- [x] Update Trackler to support `docs/EXERCISE_README_INSERT.md` in addition to the two previous names
  - issue: https://github.com/exercism/trackler/issues/62
  - PR: https://github.com/exercism/trackler/pull/63
- [x] Deploy everything
- [x] Rename the [TRACK_HINTS.md](https://github.com/exercism/request-new-language-track/blob/master/exercises/TRACK_HINTS.md) in exercism/request-new-language-track
  - PR: https://github.com/exercism/request-new-language-track/pull/29
- [x] Write a script to submit a PR to all open tracks
  - PR:  https://github.com/exercism/meta/pull/6
- [x] Wait for all the PRs to be merged
- [x] Deploy everything
- [x] Update Trackler to remove support for the old names https://github.com/exercism/trackler/pull/68

**Comment by kytrinyx** [comment]
I've prepped a script: https://github.com/exercism/meta/pull/6

**Comment by Insti** [comment]
Let me know when we're ready to remove support from the old names from trackler.

**Comment by kytrinyx** [comment]
@Insti will do!

**Comment by petertseng** [comment]
Oh nice. Thanks for doing the work.

**Comment by kytrinyx** [comment]
I added a pull request to delete the deprecation: https://github.com/exercism/trackler/pull/68
