### ISSUE TITLE
Idris / official or unofficial logo

### ISSUE THREAD

**Issue by kytrinyx** [exercism/meta#51]
As described in https://github.com/exercism/meta/issues/24, this weekend we're designing proper icons for each of the language tracks on Exercism.

In order to help speed us through this work, it would be helpful to know whether or not the language has a logo, whether official or unofficial, what that logo is, and what the usage rights of it are.

If you know things, awesome! Drop that knowledge below. If you don't but want to help do research, we will be very grateful.

Here's a template for you to fill out:

```
### Official Logo

### Unofficial Logo

### Link to Logo

### License, Usage Rights
```

For each heading, please list what you know or find out. If something is irrelevant due to something listed in an earlier heading, say `n/a` (not applicable).

We did some research a while back, and might have some useful information at the bottom of the [README.md](https://github.com/exercism/idris/blob/master/README.md). (Look for "Idris icon")

You can see whatever icon we've put together for the track in the [img directory](https://github.com/exercism/idris/tree/master/img) of the track. Sometimes this is based on something official, sometimes it's just desperation made tangible. (You'll see why we're working with real designers.)

**Comment by ilya-khadykin** [comment]
### Official Logo
From official website https://www.idris-lang.org/help-required/:
![](https://www.idris-lang.org/logo/logo-small.png)

"dragon wing" of some sort

### Unofficial Logo
There was a discussion about adding new logos:
* https://groups.google.com/forum/#!topic/idris-lang/NVAE63JlGSE

Looks like it wasn't approved

### Link to Logo
https://www.idris-lang.org/

### License, Usage Rights
From wiki https://en.wikipedia.org/wiki/Idris_(programming_language):
> License: BSD-3

Not sure if logo from official website is included though

Q: Is exercism.io using official logo?
A: Yes,
![](http://exercism.io/tracks/idris/icon)

**Comment by kytrinyx** [comment]
🌻 thank you, @m-a-ge!
