### ISSUE TITLE
Java / official or unofficial logo

### ISSUE THREAD

**Issue by kytrinyx** [exercism/meta#52]
As described in https://github.com/exercism/meta/issues/24, this weekend we're designing proper icons for each of the language tracks on Exercism.

In order to help speed us through this work, it would be helpful to know whether or not the language has a logo, whether official or unofficial, what that logo is, and what the usage rights of it are.

If you know things, awesome! Drop that knowledge below. If you don't but want to help do research, we will be very grateful.

Here's a template for you to fill out:

```
### Official Logo

### Unofficial Logo

### Link to Logo

### License, Usage Rights
```

For each heading, please list what you know or find out. If something is irrelevant due to something listed in an earlier heading, say `n/a` (not applicable).

We did some research a while back, and might have some useful information at the bottom of the [README.md](https://github.com/exercism/java/blob/master/README.md). (Look for "Java icon")

You can see whatever icon we've put together for the track in the [img directory](https://github.com/exercism/java/tree/master/img) of the track. Sometimes this is based on something official, sometimes it's just desperation made tangible. (You'll see why we're working with real designers.)

**Comment by ilya-khadykin** [comment]
### Official Logo
![](https://upload.wikimedia.org/wikipedia/en/thumb/3/30/Java_programming_language_logo.svg/300px-Java_programming_language_logo.svg.png)

Oracle released an official guideline regarding Java logo - http://www.oracle.com/us/technologies/java/java-licensing-logo-guidelines-1908204.pdf

### Unofficial Logo
There are a lot of variations, but it's hard to find copyright free version (at least in resonable amount of time)
### Link to Logo
https://upload.wikimedia.org/wikipedia/en/thumb/3/30/Java_programming_language_logo.svg/300px-Java_programming_language_logo.svg.png
### License, Usage Rights
Looks like it isn't free, quick search didn't show any copyright free version.
From https://www.oracle.com/legal/logos.html:
> Java Logos
> For Java Logo programs, visit http://www.oracle.com/us/technologies/java/java-licensing-logo-guidelines-1908204.pdf.

**Comment by iHiD** [comment]
Great. Thank you! Java was on my radar as a tricky one regarding this, so thanks for filling in the details!
