### ISSUE TITLE
JavaScript / official or unofficial logo

### ISSUE THREAD

**Issue by kytrinyx** [exercism/meta#53]
As described in https://github.com/exercism/meta/issues/24, this weekend we're designing proper icons for each of the language tracks on Exercism.

In order to help speed us through this work, it would be helpful to know whether or not the language has a logo, whether official or unofficial, what that logo is, and what the usage rights of it are.

If you know things, awesome! Drop that knowledge below. If you don't but want to help do research, we will be very grateful.

Here's a template for you to fill out:

```
### Official Logo

### Unofficial Logo

### Link to Logo

### License, Usage Rights
```

For each heading, please list what you know or find out. If something is irrelevant due to something listed in an earlier heading, say `n/a` (not applicable).

We did some research a while back, and might have some useful information at the bottom of the [README.md](https://github.com/exercism/javascript/blob/master/README.md). (Look for "JavaScript icon")

You can see whatever icon we've put together for the track in the [img directory](https://github.com/exercism/javascript/tree/master/img) of the track. Sometimes this is based on something official, sometimes it's just desperation made tangible. (You'll see why we're working with real designers.)

**Comment by stuartlangridge** [comment]
https://github.com/voodootikigod/logo.js is the unofficial logo in a zillion different formats and so on, which ought to be reusable. (It seems to be MIT-licensed.)

**Comment by iHiD** [comment]
@stuartlangridge Excellent. Thank you! :)
