### ISSUE TITLE
Julia / official or unofficial logo

### ISSUE THREAD

**Issue by kytrinyx** [exercism/meta#54]
As described in https://github.com/exercism/meta/issues/24, this weekend we're designing proper icons for each of the language tracks on Exercism.

In order to help speed us through this work, it would be helpful to know whether or not the language has a logo, whether official or unofficial, what that logo is, and what the usage rights of it are.

If you know things, awesome! Drop that knowledge below. If you don't but want to help do research, we will be very grateful.

Here's a template for you to fill out:

```
### Official Logo

### Unofficial Logo

### Link to Logo

### License, Usage Rights
```

For each heading, please list what you know or find out. If something is irrelevant due to something listed in an earlier heading, say `n/a` (not applicable).

We did some research a while back, and might have some useful information at the bottom of the [README.md](https://github.com/exercism/julia/blob/master/README.md). (Look for "Julia icon")

You can see whatever icon we've put together for the track in the [img directory](https://github.com/exercism/julia/tree/master/img) of the track. Sometimes this is based on something official, sometimes it's just desperation made tangible. (You'll see why we're working with real designers.)

**Comment by ilya-khadykin** [comment]
### Official Logo
![](https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Julia_prog_language.svg/512px-Julia_prog_language.svg.png) 
(Public Domain as stated here - https://en.wikipedia.org/wiki/File:Julia_prog_language.svg)
### Unofficial Logo
N/A

### Link to Logo
https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Julia_prog_language.svg/512px-Julia_prog_language.svg.png (Public Domain)

`librariesio/pictogram` (MIT license): https://raw.githubusercontent.com/librariesio/pictogram/master/vendor/assets/images/julia/julia.png
### License, Usage Rights
Public Domain and MIT versions are available (see above)

Q: Is exercism.io using official logo?
A: Kind of (but not really):
![](http://exercism.io/tracks/julia/icon)

P.S. what a beautiful name for the language 👍

**Comment by iHiD** [comment]
Excellent. Thanks.
