### ISSUE TITLE
Kotlin / official or unofficial logo

### ISSUE THREAD

**Issue by kytrinyx** [exercism/meta#55]
As described in https://github.com/exercism/meta/issues/24, this weekend we're designing proper icons for each of the language tracks on Exercism.

In order to help speed us through this work, it would be helpful to know whether or not the language has a logo, whether official or unofficial, what that logo is, and what the usage rights of it are.

If you know things, awesome! Drop that knowledge below. If you don't but want to help do research, we will be very grateful.

Here's a template for you to fill out:

```
### Official Logo

### Unofficial Logo

### Link to Logo

### License, Usage Rights
```

For each heading, please list what you know or find out. If something is irrelevant due to something listed in an earlier heading, say `n/a` (not applicable).

We did some research a while back, and might have some useful information at the bottom of the [README.md](https://github.com/exercism/kotlin/blob/master/README.md). (Look for "Kotlin icon")

You can see whatever icon we've put together for the track in the [img directory](https://github.com/exercism/kotlin/tree/master/img) of the track. Sometimes this is based on something official, sometimes it's just desperation made tangible. (You'll see why we're working with real designers.)

**Comment by stkent** [comment]
### Official Logo

![logo](https://user-images.githubusercontent.com/6463980/28998869-97bca9dc-7a03-11e7-8a95-3bbe9c1f7926.png)

### Unofficial Logo

n/a

### Link to Logo

Download as part of ZIP archive [here](https://resources.jetbrains.com/storage/products/kotlin/docs/kotlin_logos.zip) (also includes usage guidelines).

### License, Usage Rights

Excerpts from download above:

> DO’s
> ----
> 
> * Do use the logos to link to JetBrains website: https://www.jetbrains.com
> * Do use the logos to advertise that your product has built-in integration with a JetBrains product
> * Do use the graphics in printed or online materials, but respect the minimum size of the logo: 7.5mm in print and 50px on screen/digital.
> 
> 
> Don’ts
> ------
> 
> * Don’t change the colors of the logos
> * Don’t change the aspect ratio of the logos when resizing
> * Don’t crop the logos
> * Don’t use the black square without the beam or the product name
> * Don’t add any text on the logo 
> * Don’t sell our logos
> 
> If in doubt, please contact marketing@jetbrains.com

See full download for PDF of visual guidelines.

**Comment by stkent** [comment]
@kytrinyx please review and close if all requested information is present and correct 🖖

**Comment by iHiD** [comment]
Super helpful. Thank you!
