### ISSUE TITLE
Lisp Flavoured Erlang (LFE) / official or unofficial logo

### ISSUE THREAD

**Issue by kytrinyx** [exercism/meta#56]
As described in https://github.com/exercism/meta/issues/24, this weekend we're designing proper icons for each of the language tracks on Exercism.

In order to help speed us through this work, it would be helpful to know whether or not the language has a logo, whether official or unofficial, what that logo is, and what the usage rights of it are.

If you know things, awesome! Drop that knowledge below. If you don't but want to help do research, we will be very grateful.

Here's a template for you to fill out:

```
### Official Logo

### Unofficial Logo

### Link to Logo

### License, Usage Rights
```

For each heading, please list what you know or find out. If something is irrelevant due to something listed in an earlier heading, say `n/a` (not applicable).

We did some research a while back, and might have some useful information at the bottom of the [README.md](https://github.com/exercism/lfe/blob/master/README.md). (Look for "Lisp Flavoured Erlang (LFE) icon")

You can see whatever icon we've put together for the track in the [img directory](https://github.com/exercism/lfe/tree/master/img) of the track. Sometimes this is based on something official, sometimes it's just desperation made tangible. (You'll see why we're working with real designers.)

**Comment by ilya-khadykin** [comment]
### Official Logo
Nice logo 👍 
> The LFE logo displays an "Erlang" mug filled with liquid and a "lambda" floating on top, indicating the "flavor" of the liquid.
![](https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/LFE_%28Lisp_Flavored_Erlang%29_Logo.png/600px-LFE_%28Lisp_Flavored_Erlang%29_Logo.png)
### Unofficial Logo
N/A

### Link to Logo
https://en.wikipedia.org/wiki/File:LFE_(Lisp_Flavored_Erlang)_Logo.png

### License, Usage Rights
From wiki:
> This work has been released into the public domain by its author, Duncan McGreggor. This applies worldwide.

Q: Is exercism.io using official logo?
A: Similar, but color scheme is off
![](http://exercism.io/tracks/lfe/icon)

**Comment by kytrinyx** [comment]
It's tricky because it's got a lot of detail, but it's very clever!

Thanks :heart:
