### ISSUE TITLE
Nim / official or unofficial logo

### ISSUE THREAD

**Issue by kytrinyx** [exercism/meta#59]
As described in https://github.com/exercism/meta/issues/24, this weekend we're designing proper icons for each of the language tracks on Exercism.

In order to help speed us through this work, it would be helpful to know whether or not the language has a logo, whether official or unofficial, what that logo is, and what the usage rights of it are.

If you know things, awesome! Drop that knowledge below. If you don't but want to help do research, we will be very grateful.

Here's a template for you to fill out:

```
### Official Logo

### Unofficial Logo

### Link to Logo

### License, Usage Rights
```

For each heading, please list what you know or find out. If something is irrelevant due to something listed in an earlier heading, say `n/a` (not applicable).

We did some research a while back, and might have some useful information at the bottom of the [README.md](https://github.com/exercism/nim/blob/master/README.md). (Look for "Nim icon")

You can see whatever icon we've put together for the track in the [img directory](https://github.com/exercism/nim/tree/master/img) of the track. Sometimes this is based on something official, sometimes it's just desperation made tangible. (You'll see why we're working with real designers.)

**Comment by ilya-khadykin** [comment]
### Official Logo
From official repo https://github.com/nim-lang/Nim:
![](https://raw.githubusercontent.com/nim-lang/assets/master/Art/logo-crown.png)

Logo was designed by [Joseph Wecker](https://github.com/josephwecker)
### Unofficial Logo
N/A

### Link to Logo
https://raw.githubusercontent.com/nim-lang/assets/master/Art/logo-crown.png

### License, Usage Rights
MIT as stated in repo description

Q: Is exercism.io using official logo?
A: Yeah,
![](http://exercism.io/tracks/nim/icon)

**Comment by kytrinyx** [comment]
Lovely, thank you!
