### ISSUE TITLE
OCaml / official or unofficial logo

### ISSUE THREAD

**Issue by kytrinyx** [exercism/meta#60]
As described in https://github.com/exercism/meta/issues/24, this weekend we're designing proper icons for each of the language tracks on Exercism.

In order to help speed us through this work, it would be helpful to know whether or not the language has a logo, whether official or unofficial, what that logo is, and what the usage rights of it are.

If you know things, awesome! Drop that knowledge below. If you don't but want to help do research, we will be very grateful.

Here's a template for you to fill out:

```
### Official Logo

### Unofficial Logo

### Link to Logo

### License, Usage Rights
```

For each heading, please list what you know or find out. If something is irrelevant due to something listed in an earlier heading, say `n/a` (not applicable).

We did some research a while back, and might have some useful information at the bottom of the [README.md](https://github.com/exercism/ocaml/blob/master/README.md). (Look for "OCaml icon")

You can see whatever icon we've put together for the track in the [img directory](https://github.com/exercism/ocaml/tree/master/img) of the track. Sometimes this is based on something official, sometimes it's just desperation made tangible. (You'll see why we're working with real designers.)

**Comment by ShadowMitia** [comment]
### Official Logo
https://github.com/ocaml/ocaml-logo

### Unofficial Logo
Didn't really look.

### Link to Logo
https://github.com/ocaml/ocaml-logo

https://github.com/ocaml/ocaml-logo/tree/master/Colour/SVG
https://github.com/ocaml/ocaml-logo/tree/master/Colour/PNG

There's a lot of formats, and non colour variations as well.

### License, Usage Rights

https://github.com/ocaml/ocaml-logo/blob/master/UNLICENSE.md

Unlicense (Public domain?)


> This is free and unencumbered software released into the public domain.
> 
> Anyone is free to copy, modify, publish, use, compile, sell, or distribute this software, either in source code form or as a compiled binary, for any purpose, commercial or non-commercial, and by any means.
> 
> In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain. We make this dedication for the benefit of the public at large and to the detriment of our heirs and successors. We intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.
> 
> THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
> 
> For more information, please refer to http://unlicense.org/

**Comment by kytrinyx** [comment]
Nice! This is super helpful, thank you 🌻
