### ISSUE TITLE
Objective-C / official or unofficial logo

### ISSUE THREAD

**Issue by kytrinyx** [exercism/meta#61]
As described in https://github.com/exercism/meta/issues/24, this weekend we're designing proper icons for each of the language tracks on Exercism.

In order to help speed us through this work, it would be helpful to know whether or not the language has a logo, whether official or unofficial, what that logo is, and what the usage rights of it are.

If you know things, awesome! Drop that knowledge below. If you don't but want to help do research, we will be very grateful.

Here's a template for you to fill out:

```
### Official Logo

### Unofficial Logo

### Link to Logo

### License, Usage Rights
```

For each heading, please list what you know or find out. If something is irrelevant due to something listed in an earlier heading, say `n/a` (not applicable).

We did some research a while back, and might have some useful information at the bottom of the [README.md](https://github.com/exercism/objective-c/blob/master/README.md). (Look for "Objective-C icon")

You can see whatever icon we've put together for the track in the [img directory](https://github.com/exercism/objective-c/tree/master/img) of the track. Sometimes this is based on something official, sometimes it's just desperation made tangible. (You'll see why we're working with real designers.)

**Comment by ilya-khadykin** [comment]
### Official Logo
Looks like there is no official logo
### Unofficial Logo
This one is popular:
![](http://www.ios-blog.co.uk/wp-content/uploads/2016/01/objective-c-tutorials.png)

### Link to Logo

`librariesio/pictogram` (MIT license): https://github.com/librariesio/pictogram/blob/master/vendor/assets/images/objective-c/objective-c.png
### License, Usage Rights
MIT version is available (see above)

Q: Is exercism.io using official logo?
A: No,
![](http://exercism.io/tracks/objective-c/icon)

**Comment by kytrinyx** [comment]
Sweet, thanks!

**Comment by 9nix00** [comment]
finally,I found a awesome logo at here. thanks a lot!

I want use it in my personal resume website. Can I display the license in source code comment or I have to add link in my page?

**Comment by kytrinyx** [comment]
@wangwenpei I believe that you should be able to use the libraries.io package in your source code, which will already have the license.
