### ISSUE TITLE
PHP / official or unofficial logo

### ISSUE THREAD

**Issue by kytrinyx** [exercism/meta#62]
As described in https://github.com/exercism/meta/issues/24, this weekend we're designing proper icons for each of the language tracks on Exercism.

In order to help speed us through this work, it would be helpful to know whether or not the language has a logo, whether official or unofficial, what that logo is, and what the usage rights of it are.

If you know things, awesome! Drop that knowledge below. If you don't but want to help do research, we will be very grateful.

Here's a template for you to fill out:

```
### Official Logo

### Unofficial Logo

### Link to Logo

### License, Usage Rights
```

For each heading, please list what you know or find out. If something is irrelevant due to something listed in an earlier heading, say `n/a` (not applicable).

We did some research a while back, and might have some useful information at the bottom of the [README.md](https://github.com/exercism/php/blob/master/README.md). (Look for "PHP icon")

You can see whatever icon we've put together for the track in the [img directory](https://github.com/exercism/php/tree/master/img) of the track. Sometimes this is based on something official, sometimes it's just desperation made tangible. (You'll see why we're working with real designers.)

**Comment by yakseok** [comment]
After "googling" a little I could find the information below. I hope it helps!

### Official Logo
The official logo, according to PHP website is the oval form with PHP written inside (like the one in the img directory linked in the issue). More information: [PHP.net](http://php.net/download-logos.php).

### Unofficial Logo
As for unofficial logo, I think we can call the elephant logo. There are a lot of ways to create this one, but usually is an elephant with "PHP" written in it. More information here: [What is elePHPant and why PHP uses elephants in some logotypes?](https://php.earth/doc/community/elephpant)

### Link to Logo
![logo](http://php.net//images/logos/php-med-trans-light.gif)
More in: [PHP.net](http://php.net/download-logos.php)

### License, Usage Rights
As far I understood, you can use the logos the way you want, except if it is for selling stuff with the PHP logo in it. For example: T-shirts, mugs, etc. The official website linked above has this information:

>If you are planning on making money off of our logo (e.g. you want to make merchandise with the logo ... t-shirts, coffee mugs, pocket protectors, etc.), then you need to contact group@php.net for licensing information. For pretty much all other uses, there is no licensing requirement.

**Comment by iHiD** [comment]
@bruno-schmidt Very helpful. Thank you!

Linking to the [elephant variation](https://raw.githubusercontent.com/php-earth/PHP.earth/master/assets/images/community/elephpant.png) for when @nicolechalmers gets to this one.
