### ISSUE TITLE
Prolog / official or unofficial logo

### ISSUE THREAD

**Issue by kytrinyx** [exercism/meta#67]
As described in https://github.com/exercism/meta/issues/24, this weekend we're designing proper icons for each of the language tracks on Exercism.

In order to help speed us through this work, it would be helpful to know whether or not the language has a logo, whether official or unofficial, what that logo is, and what the usage rights of it are.

If you know things, awesome! Drop that knowledge below. If you don't but want to help do research, we will be very grateful.

Here's a template for you to fill out:

```
### Official Logo

### Unofficial Logo

### Link to Logo

### License, Usage Rights
```

For each heading, please list what you know or find out. If something is irrelevant due to something listed in an earlier heading, say `n/a` (not applicable).

We did some research a while back, and might have some useful information at the bottom of the [README.md](https://github.com/exercism/prolog/blob/master/README.md). (Look for "Prolog icon")

You can see whatever icon we've put together for the track in the [img directory](https://github.com/exercism/prolog/tree/master/img) of the track. Sometimes this is based on something official, sometimes it's just desperation made tangible. (You'll see why we're working with real designers.)

**Comment by ilya-khadykin** [comment]
### Official Logo
Couldn't find one
### Unofficial Logo
Some language implementations have their own logo versions:
(http://www.swi-prolog.org/)
![](http://www.swi-prolog.org/icons/swipl.png) 
svg: https://starbeamrainbowlabs.com/images/logos/swi-prolog.svg

GNU Prolog (http://www.gprolog.org/):
![](http://www.gprolog.org/gprolog.png)
### Link to Logo

Requires further investigation

### License, Usage Rights

Requires further investigation (depends on chosen option)

Q: Is exercism.io using official logo?
A: N/A (cute one)
![](http://exercism.io/tracks/prolog/icon)

**Comment by kytrinyx** [comment]
I do love the owl aspect, but we kind of messed up on the implementation :)

Thanks so much 🌷
