### ISSUE TITLE
TypeScript / official or unofficial logo

### ISSUE THREAD

**Issue by kytrinyx** [exercism/meta#78]
As described in https://github.com/exercism/meta/issues/24, this weekend we're designing proper icons for each of the language tracks on Exercism.

In order to help speed us through this work, it would be helpful to know whether or not the language has a logo, whether official or unofficial, what that logo is, and what the usage rights of it are.

If you know things, awesome! Drop that knowledge below. If you don't but want to help do research, we will be very grateful.

Here's a template for you to fill out:

```
### Official Logo

### Unofficial Logo

### Link to Logo

### License, Usage Rights
```

For each heading, please list what you know or find out. If something is irrelevant due to something listed in an earlier heading, say `n/a` (not applicable).

We did some research a while back, and might have some useful information at the bottom of the [README.md](https://github.com/exercism/typescript/blob/master/README.md). (Look for "TypeScript icon")

You can see whatever icon we've put together for the track in the [img directory](https://github.com/exercism/typescript/tree/master/img) of the track. Sometimes this is based on something official, sometimes it's just desperation made tangible. (You'll see why we're working with real designers.)

**Comment by ilya-khadykin** [comment]
### Official Logo
Official language repo has logo included https://github.com/Microsoft/TypeScript/blob/master/doc/logo.svg (Apache-2.0)
![](https://camo.githubusercontent.com/6effdb8103365043944db7a341e91ffe2fc234e5/68747470733a2f2f63646e2e7261776769742e636f6d2f706564726f6d616c74657a2f747970657363726970742d6c6f676f2d72656372656174696f6e2f6d61737465722f6c6f676f732f747970657363726970742d636f6c6f722d6c6f676f2e737667)
### Unofficial Logo
A community logo for TypeScript from https://github.com/remojansen/logo.ts (MIT):
![](https://raw.githubusercontent.com/remojansen/logo.ts/master/ts.png)
### Link to Logo
Official repo: https://github.com/Microsoft/TypeScript/blob/master/doc/logo.svg (vector)

`librariesio/pictogram` (MIT license): https://github.com/librariesio/pictogram/blob/master/vendor/assets/images/typescript/typescript.png

Community logos: https://github.com/remojansen/logo.ts
### License, Usage Rights
Apache-2.0 and MIT versions are available (see above)

Q: Is exercism.io using official logo?
A: Nope,
![](http://exercism.io/tracks/typescript/icon)

**Comment by kytrinyx** [comment]
👍 Thanks!
