### ISSUE TITLE
VB.NET / official or unofficial logo

### ISSUE THREAD

**Issue by kytrinyx** [exercism/meta#79]
As described in https://github.com/exercism/meta/issues/24, this weekend we're designing proper icons for each of the language tracks on Exercism.

In order to help speed us through this work, it would be helpful to know whether or not the language has a logo, whether official or unofficial, what that logo is, and what the usage rights of it are.

If you know things, awesome! Drop that knowledge below. If you don't but want to help do research, we will be very grateful.

Here's a template for you to fill out:

```
### Official Logo

### Unofficial Logo

### Link to Logo

### License, Usage Rights
```

For each heading, please list what you know or find out. If something is irrelevant due to something listed in an earlier heading, say `n/a` (not applicable).

We did some research a while back, and might have some useful information at the bottom of the [README.md](https://github.com/exercism/vbnet/blob/master/README.md). (Look for "VB.NET icon")

You can see whatever icon we've put together for the track in the [img directory](https://github.com/exercism/vbnet/tree/master/img) of the track. Sometimes this is based on something official, sometimes it's just desperation made tangible. (You'll see why we're working with real designers.)

**Comment by ilya-khadykin** [comment]
### Official Logo
It's hard to understand what official logo is, but I think this is the one:
![](https://karancode.files.wordpress.com/2015/03/visualbasic1.png)
### Unofficial Logo
This one is common too (maybe it's just an old version of official one?):
![](https://i0.wp.com/www.downloadinformer.com/wp-content/uploads/2012/12/vb-logo-3.png)

### Link to Logo
Requires further investigation

### License, Usage Rights
Free version was not found, requires further investigation 

Q: Is exercism.io using official logo?
A: No I guess,
![](http://exercism.io/tracks/vbnet/icon)

**Comment by kytrinyx** [comment]
Thanks, @m-a-ge!
