### ISSUE TITLE
Use the new nested teams feature

### ISSUE THREAD

**Issue by kytrinyx** [exercism/meta#8]
Make all tracks sub-teams of track-maintainers

https://github.com/blog/2378-nested-teams-add-depth-to-your-team-structure

**Comment by kytrinyx** [comment]
@exercism/lisp @exercism/clojure @exercism/racket Between this issue and #1 I'm thinking we should have an @exercism/lisp (or @exercism/lisps) team that has sub-teams for each lisp-y track (I think: clojure, elisp, lfe (lisp flavored erlang), racket, scheme, ... am I missing any?

**Comment by yurrriq** [comment]
LFE?

**Comment by kytrinyx** [comment]
@exercism/perl I'm considering creating perl5 and perl6 teams, nested under exercism/perl -- any objections?

**Comment by kytrinyx** [comment]
Alright, the nesting is done! We just need to decide about the various perls and lisps.

**Comment by petertseng** [comment]
https://github.com/orgs/exercism/teams looks a lot cleaner now. Nice.

I see that we can now see the language teams (as opposed to other kinds of teams) at https://github.com/orgs/exercism/teams/track-maintainers/teams. This is good.

Also this solves the problem of the various language maintainers who were not in track-maintainers (IIRC there were about 6-12 of those) for free, nice.

**Comment by kytrinyx** [comment]
> Also this solves the problem of the various language maintainers who were not in track-maintainers

Yes, this is a win!

**Comment by wobh** [comment]
One more lisp, lisp!

**Comment by kytrinyx** [comment]
@wobh how did I miss that one??!?

**Comment by petertseng** [comment]
Trying to figure out https://github.com/blog/2378-nested-teams-add-depth-to-your-team-structure (well you probably have a head start on me on that), so I take it this means there would no longer need to explicitly have members of the https://github.com/orgs/exercism/teams/track-maintainers ? As long as I am in a subteam, `@exercism/track-maintainers` and permissions will still work

nice

**Comment by kytrinyx** [comment]
> As long as I am in a subteam, @exercism/track-maintainers and permissions will still work

Yes, that's correct! I'm going to check that everyone on track-maintainers is still the maintainer of a track, and if not I'll email them before removing them. I think the right thing to do is only be members of specific teams, and let the permissions percolate up.

**Comment by ErikSchierboom** [comment]
Great improvement' :tada:

**Comment by kytrinyx** [comment]
Alrighty, I've moved the perl and lisp discussions to separate issues. Closing this!
