### ISSUE TITLE
Vim script / official or unofficial logo

### ISSUE THREAD

**Issue by kytrinyx** [exercism/meta#80]
As described in https://github.com/exercism/meta/issues/24, this weekend we're designing proper icons for each of the language tracks on Exercism.

In order to help speed us through this work, it would be helpful to know whether or not the language has a logo, whether official or unofficial, what that logo is, and what the usage rights of it are.

If you know things, awesome! Drop that knowledge below. If you don't but want to help do research, we will be very grateful.

Here's a template for you to fill out:

```
### Official Logo

### Unofficial Logo

### Link to Logo

### License, Usage Rights
```

For each heading, please list what you know or find out. If something is irrelevant due to something listed in an earlier heading, say `n/a` (not applicable).

We did some research a while back, and might have some useful information at the bottom of the [README.md](https://github.com/exercism/vimscript/blob/master/README.md). (Look for "Vim script icon")

You can see whatever icon we've put together for the track in the [img directory](https://github.com/exercism/vimscript/tree/master/img) of the track. Sometimes this is based on something official, sometimes it's just desperation made tangible. (You'll see why we're working with real designers.)

**Comment by AndrewRadev** [comment]
Hello. 

> We did some research a while back, and might have some useful information at the bottom of the README.md. (Look for "Vim script icon")

A minor thing about that -- it seems that the information you mention has been removed through https://github.com/exercism/vimscript/commit/a87478c91e94398cbe9b014bee401b7df8c6aec4. Maybe you should link to the README at an older commit? This one seems to add it:
 
https://github.com/exercism/vimscript/blob/ce85b271a7fd655e7f32e847da6239b7d7aebff4/README.md

**Comment by iHiD** [comment]
@AndrewRadev Thank you :)

For @nicolechalmers when she gets here - The logo that's been modified there is [here](http://www.vim.org/logos.php).

**Comment by AndrewRadev** [comment]
As one more side note, the logo I always use is this one: https://commons.wikimedia.org/wiki/File:Vimlogo.svg. Since it's an SVG, it's pretty convenient for different sizes (I thought that was the one that was used for https://github.com/exercism/vimscript/blob/master/img/icon.png, actually). License says GNU GPL v2+, but it's not linked at vim.org, so not sure how "official" it is.
