### ISSUE TITLE
New team structure for perl5 and perl6

### ISSUE THREAD

**Issue by kytrinyx** [exercism/meta#9]
@exercism/perl I mentioned this in a couple of issues, but I don't want it to get messy, so I'm pulling it out.

There's a new feature on GitHub that lets us nest teams: https://github.com/blog/2378-nested-teams-add-depth-to-your-team-structure

I'd like to create two new teams, perl5 and perl6 to match the track IDs of the two perl tracks, and nest these under the perl team. I'd like all memberships in `perl` to be by virtue of a membership in a specific team.

I'd love to know, for each person in the current `perl` team, are you maintaining perl5, perl6, or both? Or, for that matter neither (if you've moved on 🌷).

**Comment by kotp** [comment]
I am helping in both.  (For some measurement of "help").

**Comment by m-dango** [comment]
More 6 than 5 but still working on both.

**Comment by kytrinyx** [comment]
OK, I added the teams and fixed the structure. There are a few people who haven't been involved in over a year, so I'll email them and let them know that I'm readjusting all the teams, and if they want to get involved again, just say the word.

**Comment by kytrinyx** [comment]
I've moved the teams from the perl team to the team named for the track ID. I think we're all sorted!
