### ISSUE TITLE
Create a GitHub App that does janitorial work on the tracks

### ISSUE THREAD

**Issue by kytrinyx** [exercism/meta#96]
I'm not sure what would be useful, but here are some of the things that I'm considering.

**trigger**: a PR is submitted that changes a config file
**action**: run `configlet fmt`
  * submit the difference as a commit to the submitter's branch if allowed (maybe I need to authorize a user-to-server call using my account, because "admin")
  * if not allowed to commit, then set a failed status with a link to documentation or something

**trigger**: the description.md or metadata.yml in problem-specifications changes
**action**: regenerate the exercise README for all tracks that implement the exercise and submit a pull request

**trigger**: any of the readme templates change in a track
**action**: regenerate the exercise READMEs for all the exercises in the track and submit a pull request

**trigger**: a .meta/description.md or .meta/metadata.yml within an exercise changes
**action**: regenerate the README for that exercise

**Comment by NobbZ** [comment]
> action: run ``configlet fmt`` [and do PR if necessary]

Please use `lint` to check if `fmt` is necessary, then we get it for free in CI and the comitter has to take care of it.

> trigger: the description.md or metadata.yml in problem-specifications changes
> action: regenerate the exercise README for all tracks that implement the exercise and submit a pull request

Please don't. README and exercise might diverge then. This is actually one of the reasons why we put the READMEs into the repository.

> trigger: any of the readme templates change in a track
> action: regenerate the exercise READMEs for all the exercises in the track and submit a pull request

Reasonable, but should IMHO be done by whomever changes the template.

> trigger: a .meta/description.md or .meta/metadata.yml within an exercise changes
> action: regenerate the README for that exercise

dito

**Comment by NobbZ** [comment]
PS: the last 2 items (local changes that make rebuilding READMEs necessary) could even be checked by `lint` sub command and therefore are easily cover able by CI. 

For the remaining item I were happy about a tool which warns me when canonical stuff changes but not force me to pick those changes up right now.

**Comment by kytrinyx** [comment]
@NobbZ these are good observations. I'm trying to figure out what automation would actually help. I'm not sold on any of the suggestions I've made.

**Comment by kytrinyx** [comment]
I've thought more about this and agree with @NobbZ that these are not a good approach. I have another idea that I'm going to open an issue for.
