### ISSUE TITLE
Develop a bot that creates issues in language tracks when problem specifications are updated

### ISSUE THREAD

**Issue by kytrinyx** [exercism/meta#99]
## Background

Exercism provides a way for people to get from Hello World in a new programming language, to being comfortable with the basic syntax, datatypes, idioms, and standard library of the language.

There are 40+ active language tracks on Exercism, and 20+ language tracks that are currently in development.

Each track implements a large number of small exercises. To make this simpler, we have a collection of language-independent problem specifications that a track can use as the basis for an exercise. A language track that wants to implement the problem can use the suggested inputs/outputs for their test suite, and they can generate the README using the default description without any extra work.

Language tracks do not _need_ to follow the spec, and they can also implement exercises that do not have a generic specification.

## Problem description

For language tracks that do follow the spec for an exercise, we currently have no way of letting them know when an exercise has changed. This means that language tracks don't get the improvements when the description is clarified or a missing edge case gets added.

Because it's a whole lot of work to try to follow along in the [problem-specifications](http://github.com/exercism/problem-specifications) repository, most tracks don't update their exercises unless they (for some reason) discover that they need to.

## Suggested solution 

The goal of this project is to create a bot that will automatically create issues when there are updates to the problem specifications repository.  We want to avoid creating more work for language track maintainers, and we also want to provide a way to entice new contributors to pick up fun sized issues.

The bot would open issues that contain detailed instructions, or that points to fully fleshed out guides for how to make the change in question, and would add one or more labels (to be determined), which we could use on social media and in documentation to link people to great starter issues for getting started in open source.

1. When an existing exercise changes, the bot would post issues to all language tracks that implement the exercise
1. When a new exercise is added, the bot would post issues to all language tracks

The bot would need to be configurable.

In particular, a language track would need to be able to configure exercises that exist in the problem-specifications, but which they don't want to receive updates for (they've "forked" that exercise, and no longer follow the generic spec).

Other configuration options may also arise, such as overriding the issue template, or configuring that they don't want to receive notifications about new exercises.

## Required technologies

Such a bot can be implemented in any language, but the easiest way to implement it would be to use [Probot](https://probot.github.io/).

Probot is a **JavaScript** framework for writing GitHub Apps, and it has excellent documentation and a lively, active, supportive community including a Slack channel and weekly synchronous office hours over Google Hangouts. For support getting started, join the [Probot Community](https://probot.github.io/community/).

----

This replaces https://github.com/exercism/meta/issues/97

**Comment by Stargator** [comment]
Hey @kytrinyx,

I have been working with Probot myself for [probot-arborist](https://github.com/Stargator/probot-arborist). Sounds like a very useful approach to this issue. Looking forward to it, let me know if you could use some support.

**Comment by kytrinyx** [comment]
@Stargator that's great to know. I'm nowhere near tackling this yet, as I've got a few mountains of work that need to be done first.

**Comment by kytrinyx** [comment]
Moved to https://github.com/exercism/exercism/issues/4390
